export const setloadingStatus = "setloadingStatus"
export const settextFieldValue = "settextFieldValue"
export const setsliderValue = "setsliderValue"
export const setgroupValue = "setgroupValue"
export const setproductList = "setproductList"
export const setproductprices = "setproductprices"
export const setgroupList = "setgroupList"